/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Model(props: any) {
	const { nodes, materials }: any = useGLTF('/classroom.glb');
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes['low-poly'].geometry}
				material={nodes['low-poly'].material}>
				<meshStandardMaterial />
			</mesh>
			<mesh castShadow receiveShadow geometry={nodes.room.geometry}>
				<meshStandardMaterial />
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes['Window002|Glass_L_Windowblend|Dupli|2_glass_0']
						.geometry
				}
				material={materials['glass.001']}></mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes['Window003|Glass_L_Windowblend|Dupli|2_glass_0']
						.geometry
				}
				material={materials['glass.001']}></mesh>
		</group>
	);
}

useGLTF.preload('/classroom.glb');
